name: alarm_clock
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.3
  holiday_jp: ^0.0.8
  alarm: ^4.0.9
  timezone: ^0.9.4
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/sound1.mp3
    - assets/sounds/sound2.mp3
    - assets/sounds/sound3.mp3
